import { BLOCK_TYPES } from './config.js';

export const BLOCK_COLORS = { 
    [BLOCK_TYPES.AIR]: 'lightblue',
    [BLOCK_TYPES.GRASS]: '#6A994E',
    [BLOCK_TYPES.DIRT]: '#A98743',
    [BLOCK_TYPES.STONE]: '#A1A1AA',
    [BLOCK_TYPES.WOOD]: '#785C3D',
    [BLOCK_TYPES.LEAVES]: '#A7C957',
    [BLOCK_TYPES.COAL]: '#374151',
    [BLOCK_TYPES.IRON_ORE]: '#D1D5DB',
    [BLOCK_TYPES.SAND]: '#F0E68C',
    [BLOCK_TYPES.SEED]: '#B5A642',
    [BLOCK_TYPES.SEEDLING]: 'lightblue',
    [BLOCK_TYPES.PLANTED_GRASS]: '#A8FF8A',
};

export const BLOCK_NAMES = { 
    [BLOCK_TYPES.GRASS]: 'Grass',
    [BLOCK_TYPES.DIRT]: 'Dirt',
    [BLOCK_TYPES.STONE]: 'Stone',
    [BLOCK_TYPES.WOOD]: 'Wood',
    [BLOCK_TYPES.LEAVES]: 'Leaves',
    [BLOCK_TYPES.COAL]: 'Coal',
    [BLOCK_TYPES.IRON_ORE]: 'Iron Ore',
    [BLOCK_TYPES.SAND]: 'Sand',
    [BLOCK_TYPES.SEED]: 'Seed',
    [BLOCK_TYPES.SEEDLING]: 'Seedling',
    [BLOCK_TYPES.PLANTED_GRASS]: 'Planted Grass',
};

export const INVENTORY_BLOCKS = [ 
    BLOCK_TYPES.GRASS, BLOCK_TYPES.DIRT, BLOCK_TYPES.STONE, BLOCK_TYPES.WOOD, 
    BLOCK_TYPES.LEAVES, BLOCK_TYPES.COAL, BLOCK_TYPES.IRON_ORE, BLOCK_TYPES.SAND, BLOCK_TYPES.SEED
];

export const PASSABLE_BLOCKS = new Set([BLOCK_TYPES.AIR, BLOCK_TYPES.SEEDLING]); 